### ISSUE TITLE
wildweapons ignoring armor

### ISSUE THREAD

**Issue by TeTpaAka** [Kilarin/fractured#5]
ATM, wildweapons assumes, every entity has the fleshy armour group of 100. The correct damage calculation is stated here https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1212
This also respects the full punch interval, so you damage less when you wait too short.

Additionally, this mod only overrides tools that have been registered before it loads. To get all tools, you would have to override minetest.register_tool with something like this:

``` lua
local old_register_tool = minetest.register_tool
minetest.register_tool = function(name, item_definition)
           local old_on_use = item_definition.on_use
           item_definition.on_use = function(itemstack, user, pointed_thing)
            wildweapon_onuse(itemstack, user, pointed_thing)
                if old_on_use then
                  old_on_use(itemstack, user, pointed_thing)
                end
            end
           old_register_tool(name, item_definition)
end
```

I haven't tested it yet, but I think it should work.

**Comment by TeTpaAka** [comment]
Maybe `object:punch(puncher, time_from_last_punch, tool_capabilities, direction)` works also.

**Comment by Kilarin** [comment]
Thank you very much for the damage formula.
But wouldn't overriding minetest.register_tool just reverse the order problem?  If I loop through registered tools then wildweapons must have a depends on all mods that add tools so that they load before wildweapons runs.
BUT, if I override minetest.register_tool, then all mods that add tools must depend on wildweapons so that they will run AFTER wildweapons changes register_tool, right?

On the punch, do you mean that if I just have the tool punch it will use the built in armor calculations and bypass pvp logic?  Hmmm, that would be interesting.  Got to get some time to test.  Thanks!

**Comment by TeTpaAka** [comment]
I thought that this would be an addition to the current code. So, every tool that is already registered gets altered and any new tools would get altered when they get registered.

**Comment by Kilarin** [comment]
Ah, brilliant, Genius!

**Comment by Kilarin** [comment]
Question on punch.
When I'm within wildweapon_onuse I've got itemstack, user, pointed_thing.  How would I find a value for time_from_last_punch, and especially, how could I convert pointed_thing into direction????
Thank you!

**Comment by TeTpaAka** [comment]
You don't need to convert pointed_thing to direction. direction contains a vector from the puncher to the punched entity. It is auto filled, if both are not nil, so you don't have to deal with it.
time_from_last_punch is a lot trickier. Sadly, on_use doesn't provide a time from the last use. The only way would be (If I'm right) to save the current time on every punch with minetest.get_us_time() and subtract it from the old time.

**Comment by TeTpaAka** [comment]
https://github.com/Kilarin/fractured/commit/c181a552a3703d40ea55cb4b334d31f9fd0eceb1
